### PR TITLE
Add ability to archive completions

### LINKED ISSUE #29: Inability to archive completions
When a certification window opens a course, its activities are reset; however the OJT activity module is NOT reset and any exisitng topic completions, comment and uploads are kept intact.

### PR DESCRIPTION
**Pull request by alexmorrisnz**
Fixes #29

### CODE REVIEW

**Comment by alexmorrisnz** [comment]
I'll put this on the T12 branch once merged, there is no difference between the T12 and T13 version of this.

**Comment by alexmorrisnz** [comment]
Tested and confirmed working on T13.

**Comment by sergeyandrogogic** [comment]
Hi guys, is there a chance this would be added to master (for T12 and T13) any time soon? This is a massive showstopper for many of our clients, as certifications fail to work properly.

**Comment by DrCuriosity** [comment]
Hi @sergeyandrogogic,

Apologies for the long delay. I have merged this in on `master` now; I hope to get it through onto the `OJT_12` branch as well soon.

**Comment by DrCuriosity** [comment]
This feature is now in `OJT_12` as well.

**Pull request merged**
